# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gate_service/proto/gate_stream.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gate_service/proto/gate_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gate_service/proto/gate_stream.proto\x12\x11nextwaves.gate.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n\x10GetStatusRequest\"(\n\x12WatchEventsRequest\x12\x12\n\nevent_type\x18\x01 \x03(\t\"\x96\x01\n\nGateStatus\x12\x0f\n\x07gate_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05ready\x18\x03 \x01(\x08\x12/\n\x0bobserved_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xca\x01\n\tGateEvent\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12/\n\x0boccurred_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07gate_id\x18\x05 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\x12%\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct2\xba\x01\n\x11GateStreamService\x12O\n\tGetStatus\x12#.nextwaves.gate.v1.GetStatusRequest\x1a\x1d.nextwaves.gate.v1.GateStatus\x12T\n\x0bWatchEvents\x12%.nextwaves.gate.v1.WatchEventsRequest\x1a\x1c.nextwaves.gate.v1.GateEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gate_service.proto.gate_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSREQUEST']._serialized_start=122
  _globals['_GETSTATUSREQUEST']._serialized_end=140
  _globals['_WATCHEVENTSREQUEST']._serialized_start=142
  _globals['_WATCHEVENTSREQUEST']._serialized_end=182
  _globals['_GATESTATUS']._serialized_start=185
  _globals['_GATESTATUS']._serialized_end=335
  _globals['_GATEEVENT']._serialized_start=338
  _globals['_GATEEVENT']._serialized_end=540
  _globals['_GATESTREAMSERVICE']._serialized_start=543
  _globals['_GATESTREAMSERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
