# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gate_service.proto import gate_stream_pb2 as gate__service_dot_proto_dot_gate__stream__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gate_service/proto/gate_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GateStreamServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/nextwaves.gate.v1.GateStreamService/GetStatus',
                request_serializer=gate__service_dot_proto_dot_gate__stream__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=gate__service_dot_proto_dot_gate__stream__pb2.GateStatus.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/nextwaves.gate.v1.GateStreamService/WatchEvents',
                request_serializer=gate__service_dot_proto_dot_gate__stream__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=gate__service_dot_proto_dot_gate__stream__pb2.GateEvent.FromString,
                _registered_method=True)


class GateStreamServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=gate__service_dot_proto_dot_gate__stream__pb2.GetStatusRequest.FromString,
                    response_serializer=gate__service_dot_proto_dot_gate__stream__pb2.GateStatus.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=gate__service_dot_proto_dot_gate__stream__pb2.WatchEventsRequest.FromString,
                    response_serializer=gate__service_dot_proto_dot_gate__stream__pb2.GateEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nextwaves.gate.v1.GateStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nextwaves.gate.v1.GateStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GateStreamService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nextwaves.gate.v1.GateStreamService/GetStatus',
            gate__service_dot_proto_dot_gate__stream__pb2.GetStatusRequest.SerializeToString,
            gate__service_dot_proto_dot_gate__stream__pb2.GateStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nextwaves.gate.v1.GateStreamService/WatchEvents',
            gate__service_dot_proto_dot_gate__stream__pb2.WatchEventsRequest.SerializeToString,
            gate__service_dot_proto_dot_gate__stream__pb2.GateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
